### ISSUE TITLE
这个怎么安装呀？

### ISSUE THREAD

**Issue by draft-jay** [nonameShijian/noname#1]

**Comment by nonameShijian** [comment]
不是，这个是开发的项目，需要用一些别的命令打包成exe的

**Comment by ciddiaz** [comment]
那么希望游玩诗笺版Windows端的玩家应该到哪里去找，或者怎么加工下载好的这个仓库呢？网上的资源都是Android端的。
谢谢！

**Comment by nonameShijian** [comment]
> 那么希望游玩诗笺版Windows端的玩家应该到哪里去找，或者怎么加工下载好的这个仓库呢？网上的资源都是Android端的。
> 谢谢！

安装nodejs，然后项目的根目录使用cmd运行npm install后，运行Package.json中你需要打包对应平台的命令

**Comment by ciddiaz** [comment]
项目Readme中说将新出现的文件夹“无名杀-darwin-x64”移动到“应用程序”，但是仓库中乃至我计算机的所有硬盘没有叫这个名字的目录啊

**Comment by nonameShijian** [comment]
> 项目Readme中说将新出现的文件夹“无名杀-darwin-x64”移动到“应用程序”，但是仓库中乃至我计算机的所有硬盘没有叫这个名字的目录啊

“MAC”

**Comment by ciddiaz** [comment]
Windows平台打包完成后直接将该文件夹留在原位吗，还是使用仓库根目录的“noname-server.exe”启动吗？
无论打不打包，用noname-server.exe启动，都会有拖拽读取和应用配置应用的报错，而且“关于”选项卡只有一个版本号，没有按钮更新，也没有下载素材的地方
打扰您了，深感抱歉！

**Comment by nonameShijian** [comment]
打包之后你爱放哪都行，用根目录下的exe

**Comment by ciddiaz** [comment]
在Windows系统下打包完之后，目录noname-main\无名杀-darwin-x64\无名杀.app\Contents\Resources\app里确实也有一个noname-server.exe，但是使用这个exe启动依然产生如下报错，依然存在选项-其他-更新中只显示一个版本号，无法检查游戏更新，也无法下载素材的问题


['错误文件: http://localhost:8089/extension/拖拽读取/extension.js
错误信息: require is not defined
行号: 4
列号: 13
无名杀版本: 1.10.16
event.name: 
event.step: 0
-------------
1| import { lib, game, ui, get, ai, _status } from '../../noname.js';
2| game.import("extension", function () {
3| 	/** 解压文件方法 */
4| ⚠️	const fs = require("fs");
5| 	const path = require('path');
6| 
7| 	const { versions } = process;
8| 	const electronVersion = parseFloat(versions.electron);
9| 	let remote;
10| 	if (electronVersion >= 14) {

-------------
ReferenceError: require is not defined
    at http://localhost:8089/extension/拖拽读取/extension.js:4:13
    at Game.loadExtension (http://localhost:8089/noname/game/index.js:1966:75)
    at Game.import (http://localhost:8089/noname/game/index.js:1941:25)
    at http://localhost:8089/extension/拖拽读取/extension.js:2:12']
0: '错误文件: http://localhost:8089/extension/拖拽读取/extension.js
错误信息: require is not defined
行号: 4
列号: 13
无名杀版本: 1.10.16
event.name: 
event.step: 0
-------------
1| import { lib, game, ui, get, ai, _status } from '../../noname.js';
2| game.import("extension", function () {
3| 	/** 解压文件方法 */
4| ⚠️	const fs = require("fs");
5| 	const path = require('path');
6| 
7| 	const { versions } = process;
8| 	const electronVersion = parseFloat(versions.electron);
9| 	let remote;
10| 	if (electronVersion >= 14) {

-------------
ReferenceError: require is not defined
    at http://localhost:8089/extension/拖拽读取/extension.js:4:13
    at Game.loadExtension (http://localhost:8089/noname/game/index.js:1966:75)
    at Game.import (http://localhost:8089/noname/game/index.js:1941:25)
    at http://localhost:8089/extension/拖拽读取/extension.js:2:12'
length: 1
 
['错误文件: http://localhost:8089/extension/应用配置/extension.js
错误信息: process is not defined
行号: 3
列号: 23
无名杀版本: 1.10.16
event.name: 
event.step: 0
-------------
1| import { lib, game, ui, get, ai, _status } from '../../noname.js';
2| game.import("extension", function() {
3| ⚠️	const { versions } = process;
4| 	const electronVersion = parseFloat(versions.electron);
5| 	
6| 	if (isNaN(electronVersion) || electronVersion < 13) {
7| 		throw '此版本应用不适用【应用配置】';
8| 	}
9| 	

-------------
ReferenceError: process is not defined
    at http://localhost:8089/extension/应用配置/extension.js:3:23
    at Game.loadExtension (http://localhost:8089/noname/game/index.js:1966:75)
    at Game.import (http://localhost:8089/noname/game/index.js:1941:25)
    at http://localhost:8089/extension/应用配置/extension.js:2:12']

**Comment by Crazy-A2** [comment]
@ciddiaz Windows 64位系统用 `npm run packageWin64`  命令打包
你要是32位系统就 `npm run packageWin32`  

![Image](https://github.com/user-attachments/assets/9d12e9cb-45f6-4709-9c3b-832e059c3299)

在系统信息里看你是64位还是32位系统

![Image](https://github.com/user-attachments/assets/2773fd08-622f-4586-b80c-a348e744e8f4)
